### ISSUE TITLE
Support for configuring dedicated gateway nodes in submariner addon

### ISSUE THREAD

**Issue by aswinsuryan** [stolostron/console#1096]
The submariner supports deploying gateway nodes in a newly deployed worker node and in existing one in cloud providers like GCP and plans to support both modes in Azure and Openstack.

This is not configurable in the ACM submariner addon UI and in GCP it would default to using the existing node.

As a part of this enhancement request

1. A new configuration option shall be added to the UI(like a dedicated node checkbox)
2. It can default to using the existing node as the gateway node.
3. A warning info can be shown in the UI which mentions the cost implications if the dedicated node option is selected.

**Comment by KevinFCormier** [comment]
FYI @bweidenb @sho @vthapar

Not sure if this is a new request or part of an existing JIRA item.

**Comment by bweidenb** [comment]
Thanks @KevinFCormier  I have added this topic to Submariner 2.5 UX & Submariner ACM UI sync call docs as an agenda item and future feature consideration.

**Comment by nyechiel** [comment]
@KevinFCormier this is a duplicate of https://github.com/stolostron/backlog/issues/19296. Should I close it and keep the other one in the backlog repo?

**Comment by nyechiel** [comment]
Duplicate of https://github.com/stolostron/backlog/issues/19296
